import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import NewsTicker from "./components/NewsTicker";
import DiwaliCelebration from "./components/DiwaliCelebration";
import { AuthProvider } from "../contexts/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <AuthProvider>
          <DiwaliCelebration/>
          <Navbar/>
          <NewsTicker/>
          {children}
          <Footer/>
        </AuthProvider>
      </body>
    </html>
  );
}
